name: SampleFeatures
version: '${project.version}'
main: me.jordanfails.samplefeatures.SampleFeatures
api-version: 1.8.9
depend:
  - Lazarus
  - LunarClient-API
commands:
  arevive:
    description: a neat command for all your admin problems
    permission: hcf.revive.admin
  checkdeathban:
    description: a neat command to check your deathban status
  checkrank:
    description: check your current highest rank with check rank
  finfo:
    description: a cool command to check the information on a faction.
  fpunish:
    description: a cool command to punish a whole faction.
  freerank:
    description: a cool command to get a free rank.
  timeline:
    description: a cool command to check the timeline of other staff members!