name: SampleFeatures
version: '1.0-SNAPSHOT'
main: me.jordanfails.samplefeatures.SampleFeatures
api-version: 1.8.9
depend:
  - Lazarus
  - LunarClient-API
commands:
  arevive:
    description: a neat command for all your admin problems
    permission: hcf.revive.admin
  checkdeathban:
    description: a neat command to check your deathban status
  checkrank:
    description: check your current highest rank with check rank
  delay:
    description: a cool command to delay chat.
    permission: hcf.staff.delaychat
  finfo:
    description: a cool command to check the information on a faction.
  fpunish:
    description: a cool command to punish a whole faction.
  freerank:
    description: a cool command to get a free rank.
  serverinfo:
    description: a cool command to show server info
    permission: hcf.command.serverinfo
  timeline:
    description: a cool command to check the timeline of other staff members!
  youtube:
    description: a cool command to check the requirements for youtube rank.